group=org.leavesmc.leaves
version=26.1.2-R0.1-SNAPSHOT
leavesXVersion=1.1.0
mcVersion=26.1.2
paperRef=e4e17fc90d31c3dca6de8bebc87c741749f8f3df
channel=STABLE
preVersion=false
paper.runDisableWatchdog=true

# This is the current API version for use in (paper-/leaves-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.1.2

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
